# Based on the default default .travis.yml for usage with Stack.
# See https://docs.haskellstack.org/en/stable/travis_ci/.

language: c

cache:
  directories:
    - $HOME/.stack/

addons:
  apt:
    packages:
      - libgmp-dev

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - stack setup --no-terminal

script:
  - stack build -j2 --no-terminal
  - stack test -j2 --no-terminal
  # As CI is running on a Debian-like system, test building
  # the package here too.
  - cd package && VERSION=0.0.0 ./build-package.sh
