language: nix

# Do not build other branches than these, pull requests get built anyway, and in
# the end it is only the result of the testing branch that matters. In theory
# the commits that get pushed to master should have been built in testing
# already, but sometimes I still push manually, and of course the evergreen
# build status badge needs to come from somewhere.
branches:
  only:
  - master
  - testing

# Do not spam me with build status emails.
notifications:
  email: false

cache:
  directories:
  - $HOME/.stack
  - $TRAVIS_BUILD_DIR/.stack-work

before_install:
  # Bring all the tools from the pinned build environment into the PATH.
  - export PATH=$(nix-build --no-out-link)/bin:$PATH

install:
  # Set up the Haskell toolchain.
  - stack setup

script:
  - stack --no-terminal build --split-objs
  - stack --no-terminal test --split-objs

    # Match the licenses of dependencies agains a whitelist,
    # and fail if anything is not whitelisted. Grep -v returns
    # 1 if nothing matches, so we invert it with a ! prefix.
  - "! stack ls dependencies --license | egrep -v 'Apache-2|BSD2|BSD3|MIT|PublicDomain'"
