# The `ghc` resolver does not use any stackage snapshot, instead, it only
# provides those packages that are packaged with GHC.
# Via nix (see `nix.shell-file` down below), we provide a GHC that comes
# with all the packages we need. Therefore, stack does not have to
# download or build any snapshot packages, they all come directly from nixpkgs.
resolver: ghc-9.2

# This makes stack pick up our nix environment for building by default.
nix:
  enable: true
  shell-file: stack-shell.nix
  path: ["nixpkgs=./nixpkgs-pinned.nix"]
