"""Something changes

Revision ID: 8173ca21b11d
Revises: db6fced84dcd
Create Date: 2022-01-14 9:40:16.379321

"""

import sqlalchemy as sa

from alembic import op  # type: ignore


# revision identifiers, used by Alembic.
revision = '8173ca21b11d'
down_revision = 'db6fced84dcd'

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
